openapi: 3.0.1
info:
  title: RUTPAM API
  version: 1.0.0
  description: "Esta es la API que provee de datos de forma centralizada 
  al visor RUTPAM. Estandariza información general de la red de transportes 
  de múltiples formados y modelos bajo una integración general"
  #termsOfService: http://example.com/terms/
  contact:
    name: Nestor Lora
    email: nestorlora@geeklab.es
    #url:
  license:
    name: MIT
    #url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
- url: http://rutpam.titan.geeklab.es/api
#  description: Servidor de desarrollo HTTP
#- url: https://rutpam.titan.geeklab.es/api
#  description: Servidor de desarrollo HTTPS
#- url: https://rutpam.geeklab.es/api
#  description: Servidor de Producción HTTP
#- url: https://rutpam.geeklab.es/api
#  description: Servidor de desarrollo HTTPS

# ---------------------------------------

paths:
  /appdb:
    get:
      summary: Base de Datos completa para la aplicación
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
  /linea/{id}:
    get:
      summary: ''
      description: ''
      operationId: ''
      parameters:
          - name: id
            in: path
            description: Identificador de la línea
            required: true
            schema:
                type: integer
                format: int64
      responses:
        default:
          description: Default error sample response
  /linea/{id}/extendida:
    get:
      summary: ''
      description: ''
      operationId: ''
      parameters:
          - name: id
            in: path
            description: Identificador de la línea
            required: true
            schema:
                type: integer
                format: int64
      responses:
        default:
          description: Default error sample response
# ---------------------------------------

components:
  schemas:
    Linea:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "Identificador de la línea en la base de datos"
          example: 134846
        red:
          type: integer
          format: int32
          description: "Identificador de la red en la base de datos"
          example: 2
        eid:
          type: string
          description: "Identificador externo de la línea en su red"
          example: 41
        codigo:
          type: string
          description: "Nombre corto o código que ven los viajeros"
          example: "N1"
        nombre:
          type: string
          description: "Nombre de la línea"
          example: "Puerta Blanca - Alameda Principal - El Palo"
        sentidos:
          type: array
          items: 
            type: integer
            format: integer64
          description: ID de los ramales y variaciones con sus itinerarios posibles en la línea
        modo:
          type: integer
          format: int32
          description: Identificador del modo de transporte en la base de datos
          example: 1
        #icono:
        operadores:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int32
                description: Identificador del operador en la base de datos
                example: 7
              rol:
                type: array
                items:
                  type: string
                  description: Rol del operador en la línea
                  example: "Regulación, Op. Flota"
          description: Listado de operadores involucrados y sus competencias en relación a la línea
      required:
      - id
      - red
      - eid
      - codigo
      - nombre
      - sentidos
      - modo
      - operadores

    LineaExtendida:
      allOf:
        - $ref: '#/components/schemas/Linea'
        - type: object
          properties:
            color:
              type: string
              description: Color Hex de la línea
              example: 00FF00
            color_texto:
              type: string
              description: Color Hex del texto para los badges de la línea
              example: FFFFFF
            tipo:
              type: string
              description: >
                Extensión de tipo de ruta GTFS.
                Leyenda en [Google Dev](https://developers.google.com/transit/gtfs/reference/extended-route-types?hl=es)

    Itinerario:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Identificador del itinerario en la base de datos
          example: 1654135
        sentido:
          type: integer
          format: int64
          description: Identificador del sentido (Ida/Vuelta/Circular/Posicionamiento)
          example: 1
        destino:
          type: string
          description: Headsign o indicacion de destino
          example: El Palo
        description:
          type: string
          description: Descripción del sentido
          example: Ida. Itinerario 1
        circular:
          type: boolean
          description: La primera parada va después de la última
          example: true
        paradas:
          type: array
          items:
            type: integer
            format: int64
            description: Identificador de la parada en la base de datos
            example: 651385
        trazado:
          $ref: '#/components/schemas/Trazado'
      
    ItinerarioExtendido:
      allOf:
      - $ref: '#/components/schemas/Linea'
      - type: object
        properties:
          eid:
            type: string
            description: "Identificador externo del itinerario en su red"
            example: 1037S

    Trazado:
      type: object
      properties:
        pol:
          type: array
          description: Polilínea del trazado
          items:
            $ref: '#/components/schemas/LatLong'
        color:
          type: string
          description: Color HTML de la polilínea
          example: "#009639"
        transparencia:
          type: number
          format: float
          description: Porcentaje de transparencia de la polilínea
          example: 1.0
        multisentido:
          type: boolean
          description: Este trazado es válido para todos los sentidos de la línea (metro, tren)
          example: false
      required:
      - pol
      - color
      - especiales

    # Alteracion:
    #   type: object
    #   description: Modificaciones temporales en una línea o imprevistos
    #   properties:
    #     tipo:
    #       type: string
    #       description: Naturaleza de la modificación
    #       example: Obras
    #     info:
    #       type: string
    #       description: Nombre o información de la alteración
    #       example: Semana Santa 2019
    #     prioridad:
    #       type: integer
    #       format: int32
    #       description: Indicador de la prioridad que tiene la alteración sobre otras alteraciones que afecten los mismos elementos
    #       example: 3
    #     afectados:
    #       type: object
    #       properties:
    #         itinerarios:
    #           type: array
    #           items:
    #             type: integer
    #             format: int64
    #             description: Identificador del itinerario en la base de datos
    #             example: 1654135
    #         vehiculos:
    #           type: array
    #           items:
    #             type: integer
    #             format: int64
    #             description: Identificador del itinerario en la base de datos
    #             example: 1654135
    #     modificaciones:
    #       type: object
    #       properties:

    Parada:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: Identificador de la parada en la base de datos
          example: 5423
        nombre:
          type: string
          description: Nombre de la parada
          example: Alameda Principal - Sur
        direccion:
          type: string
          description: Dirección postal de la parada (si la tiene)
          example: Paseo del Parque 21
        nucleo:
          type: integer
          format: int32
          description: Identificador del núcleo al que pertenece la parada
          example: 175
        zona:
          type: integer
          format: int32
          description: Identificador de la zona a la que pertenece la parada
          example: 3
        itinerarios:
          type: array
          items:
            type: integer
            format: int64
            description: Identificador del itinerario
            example: 3278
        ubicacion:
          $ref: '#/components/schemas/LatLong'
        modo:
          type: integer
          format: int64
          description: Identificador del modio de transporte
          example: 2
        red:
          type: integer
          format: int64
          description: Identificador de la red
          example: 7

    #Estacion
    #TODO
    #Grupo de paradas de la misma estación

    #Correspondencia
    #TODO
    #Grupo de estaciones o paradas sueltas que están cerca

    #Expedicion
    #TODO

    #Vehiculo
    #TODO

    Red:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        

    Operador:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: Identificador del operador
          example: 5
        nombre:
          type: string
          description: Nombre del operador
          example: "Avanza Movilidad Urbana, S.L.U"
        telefono:
          type: string
          description: Telefono de atención al viajero
          example: 952000000
        web:
          type: string
          description: URL de la web
          example: https://emtmalaga.es
        email:
          type: string
          description: Email de contacto
          example: clientes@emtsam.es
        direccion:
          type: string
          description: Dirección postal
          example: Camino de San Rafael s/n 29001 - Málaga
      required:
      - id
      - nombre

    #Noticia
    
    #Nucleo
    
    #Modo

    #Zona

    #Tipo de ruta
    #https://developers.google.com/transit/gtfs/reference/extended-route-types?hl=es

    LatLong:
      type: object
      properties:
        lat:
          type: number
          format: float
          example: 36.6916079
        lng:
          type: number
          format: float
          example: -4.4561347
      required:
      - lat
      - lng

    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
