openapi: 3.0.1
info:
  title: RUTPAM API
  version: 0.3-dev
  description: >
    This API defines the methods and objects to provide and receive data from/to a RUTPAM Server.
    The design extends GTFS specification to a more abstract and complete knowledge base about the stored public transit networks.
  contact:
    name: Néstor Lora
    email: nestorlora@geeklab.es
  license:
    name: MIT
servers:
  - url: 'http://localhost:5000'
    description: Development local HTTP Server
# Method legend:
# GET - Get data (not modified)
# POST - Create resource if not exists
# PUT - Create resource
# DELETE - Delete/Disable/Expire resource
# PATCH - Edit resource
paths:
  /info:
    $ref: './paths/info.yml'
#  /auth - TODO
  /networks:
    $ref: './paths/networks.yml'
  /networks/{id}:
    $ref: './paths/networks.{id}.yml'
components:
  schemas:
    Network:
      $ref: './schemas/Network.yml'
    ApiResponse:
      $ref: './schemas/ApiResponse.yml'
    objectId:
      $ref: './schemas/objectId.yml'
    url:
      type: string
      example: 'http://example.com/resource'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Server
    description: Server status and authentication
  - name: Networks
    description: Transit networks
  - name: Routes
  - name: Subroutes
  - name: Stops
  - name: Stations
  - name: Transfers
  - name: Paths
  - name: Points
  - name: Agencies
  - name: Zones
  - name: Towns
